crm/bands/urls.py
from django.urls import path
from .views import BandsListView, BandCreateView, BandUpdateView, BandDeleteView, BandDetailView
app_name = 'bands'

urlpatterns = [
    path('', BandsListView.as_view(), name="band-list"),
    path('<int:pk>/', BandDetailView.as_view(), name='band-detail'),
    path('create/', BandCreateView.as_view(), name='band-create'),
    path('<int:pk>/update/', BandUpdateView.as_view(), name='band-update'),
    path('<int:pk>/delete/', BandDeleteView.as_view(), name='band-delete'),

]

crm/sccrm/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path, include
from musicians.views import LandingPageView, SignupView
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPageView.as_view(), name='landing-page'),
    path('musicians/', include('musicians.urls', namespace="bands")),
    path('bands/', include('bands.urls', namespace="musicians")),
    path('signup/', SignupView.as_view(), name='signup'),
    path('reset-password-done/', PasswordResetView.as_view(), name='reset-password-done'),
    path('reset-password/', PasswordResetDoneView.as_view(), name='reset-password'),
    path('reset-password-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='reset-password-confirm'),
    path('reset-password-complete/', PasswordResetCompleteView.as_view(), name='reset-password-complete'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout')
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

crm/bands/models.py
from django.db import models

# Create your models here.

crm/bands/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

User = get_user_model()


class BandModelForm(forms.ModelForm):
    class Meta:
        model = User
        fields = (
            'email',
            'username',
            'first_name',
            'last_name'
        )

crm/bands/views.py
from django.shortcuts import render
from django.core.mail import send_mail
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import reverse
from musicians.models import Band
from .forms import BandModelForm
from .mixins import OrganisorAndLoginRequiredMixin
import random 

# Create your views here.

class BandsListView(OrganisorAndLoginRequiredMixin,generic.ListView):
    template_name: str = "bands/band_list.html"

    def get_queryset(self):
        organisation = self.request.user.userprofile
        return Band.objects.filter(organisation=organisation)

class BandCreateView(OrganisorAndLoginRequiredMixin, generic.CreateView):
    template_name = "bands/band_create.html"
    form_class = BandModelForm

    def get_success_url(self):
        return reverse("bands:band-list")
    

    def form_valid(self, form):
        user = form.save(commit=False)
        user.is_agent = True
        user.is_organisor = False
        user.set_password(f"{random.randint(0, 1000000)}")
        user.save()
        Band.objects.create(
            user=user,
            organisation=self.request.user.userprofile
        )
        send_mail(
            subject="You are invited to be a band",
            message="You were added as a band on DJCRM. Please come login to start working.",
            from_email="band@test.com",
            recipient_list=[user.email]
        )
        return super(BandCreateView, self).form_valid(form)

class BandDetailView(OrganisorAndLoginRequiredMixin, generic.DetailView):
    template_name = "bands/band_detail.html"
    context_object_name = "band"

    def get_queryset(self):
        organisation = self.request.user.userprofile
        return Band.objects.filter(organisation=organisation)

class BandUpdateView(OrganisorAndLoginRequiredMixin, generic.UpdateView):
    template_name = "bands/band_update.html"
    form_class = BandModelForm

    def get_success_url(self):
        return reverse("bands:band-list")

    def get_queryset(self):
        organisation = self.request.user.userprofile
        return Band.objects.filter(organisation=organisation)

class BandDeleteView(OrganisorAndLoginRequiredMixin, generic.DeleteView):
    template_name = "bands/band_delete.html"
    context_object_name = "band"

    def get_success_url(self):
        return reverse("bands:band-list")

    def get_queryset(self):
        organisation = self.request.user.userprofile
        return Band.objects.filter(organisation=organisation)

crm/bands/templates/bands/band_create.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}

<div class="max-w-lg mx-auto">

    <div class="py-5 border-b border-gray-200">
        <a class="hover:text-blue-500" href="{% url 'bands:band-list' %}">Go back to bands</a>
    </div>

    <h1 class="text-4xl text-gray-800">Create a new band</h1>
    <form method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">Submit</button>
    </form>

</div>

{% endblock content %}

crm/bands/templates/bands/band_delete.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}
<div class="max-w-lg mx-auto">
    <div class="py-5 border-b border-gray-200">
        <a class="hover:text-blue-500" href="{% url 'bands:band-list' %}">Go back to bands</a>
    </div>
    <h1 class="text-3xl text-gray-800">Are you sure you want to delete this band?</h1>
    <form method="post" class="mt-5">
        {% csrf_token %}
        {{ form|crispy }}
        <button type="submit" class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">Submit</button>
    </form>
    <div class="py-5 mt-5">
        <a class="hover:text-blue-500" href="{% url 'bands:band-detail' object.pk %}">Cancel</a>
    </div>
</div>
{% endblock content %}

crm/bands/templates/bands/band_detail.html
{% extends "base.html" %}

{% block content %}

<section class="text-gray-700 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
      <div class="lg:w-4/5 mx-auto flex flex-wrap">
        <div class="w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
            <h2 class="text-sm title-font text-gray-500 tracking-widest">Band</h2>
            <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ band.user.username }}</h1>
            <div class="flex mb-4">
                <a href="{% url 'bands:band-detail' band.pk %}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">
                    Overview
                </a>
                <a href="{% url 'bands:band-update' band.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                    Update Details
                </a>    
            </div>
            <div class="flex border-t border-gray-300 py-2">
                <span class="text-gray-500">Full Name</span>
                <span class="ml-auto text-gray-900">{{ band.user.first_name }} {{ band.user.last_name }}</span>
            </div>
            <div class="flex border-t border-gray-300 py-2">
                <span class="text-gray-500">Email</span>
                <span class="ml-auto text-gray-900">{{ band.user.email }}</span>
            </div>
        </div>
      </div>
    </div>
  </section>
{% endblock content %}

crm/bands/templates/bands/band_list.html
{% extends "base.html" %}

{% block content %}
    <section class="text-gray-700 body-font">
        <div class="container px-5 py-24 mx-auto flex flex-wrap">
            <div class="w-full mb-6 py-6 flex justify-between items-center border-b border-gray-200">
                <div>
                    <h1 class="text-4xl text-gray-800">Bands</h1>
                </div>
                <div>
                    <a class="text-gray-500 hover:text-blue-500" href="{% url 'bands:band-create' %}">Create a new band</a>
                </div>
            </div>

            <div class="flex flex-col w-full">
                <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
                <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
                    <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
                    <table class="min-w-full divide-y divide-gray-200">
                        <thead class="bg-gray-50">
                            <tr>
                                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Full Name
                                </th>
                                <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                                Email
                                </th>
                                <th scope="col" class="relative px-6 py-3">
                                <span class="sr-only">Edit</span>
                                </th>
                            </tr>
                        </thead>
                        <tbody>
                            {% for band in object_list %}
                                <tr class="bg-white">
                                    <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                                        {{ band.user.first_name }} {{ band.user.last_name }}
                                    </td>
                                    <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                        {{ band.user.email }}
                                    </td>
                                    <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                                        <a href="{% url 'bands:band-update' band.pk %}" class="text-indigo-600 hover:text-indigo-900">
                                            Edit
                                        </a>
                                    </td>
                                </tr>
                            {% empty %}

                            <p>There are currently no bands</p>

                            {% endfor %}
                        </tbody>
                    </table>
                    </div>
                </div>
                </div>
            </div>

        </div>
      </section>
{% endblock content %}

crm/bands/templates/bands/band_update.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}

<section class="text-gray-700 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
      <div class="lg:w-4/5 mx-auto flex flex-wrap">
        <div class="w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
            <h2 class="text-sm title-font text-gray-500 tracking-widest">Band</h2>
            <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ band.user.username }}</h1>
            <div class="flex mb-4">
                <a href="{% url 'bands:band-detail' band.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                    Overview
                </a>
                <a href="{% url 'bands:band-update' band.pk %}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">
                    Update Details
                </a>
            </div>
            <form form method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">Submit</button>
            </form>
            <div class="mt-5 py-5 border-t border-gray-200">
                <a href="{% url 'bands:band-delete' band.pk %}" class="w-1/2 mt-3 text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">
                    Delete
                </a>
            </div>
        </div>
      </div>
    </div>
  </section>
{% endblock content %}