crm/bands/urls.py
from django.urls import path
from .views import BandsListView, BandCreateView, BandUpdateView, BandDeleteView, BandDetailView
app_name = 'bands'

urlpatterns = [
    path('', BandsListView.as_view(), name="band-list"),
    path('<int:pk>/', BandDetailView.as_view(), name='band-detail'),
    path('create/', BandCreateView.as_view(), name='band-create'),
    path('<int:pk>/update/', BandUpdateView.as_view(), name='band-update'),
    path('<int:pk>/delete/', BandDeleteView.as_view(), name='band-delete'),

]

crm/musicians/urls.py
from django.urls import path
from .views import (musician_list, musician_detail, musician_create, musician_update, musician_delete, MusicianListView, MusicianDetailView, MusicianCreateView,MusicianUpdateView, MusicianDeleteView, AssignBandView, CategoryListView
)

app_name = "musicians"

urlpatterns = [
path('', MusicianListView.as_view(), name='musician-list'),
path('<int:pk>/', MusicianDetailView.as_view(), name='musician-detail'),
path('<int:pk>/update/', MusicianUpdateView.as_view(), name='musician-update'),
path('<int:pk>/delete/', MusicianDeleteView.as_view(), name='musician-delete'),
path('create/', MusicianCreateView.as_view(), name='musician-create'),
path('create/', MusicianCreateView.as_view(), name='musician-create'),
path('<int:pk>/assign-band/', AssignBandView.as_view(), name='assign-band'),
path('categories/', CategoryListView.as_view(), name='category-list'),
path('categories/<int:pk>/', CategoryListView.as_view(), name='category-detail'),
]

crm/sccrm/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.contrib.auth.views import LoginView, LogoutView, PasswordResetView, PasswordResetDoneView, PasswordResetConfirmView, PasswordResetCompleteView
from django.urls import path, include
from musicians.views import LandingPageView, SignupView
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', LandingPageView.as_view(), name='landing-page'),
    path('musicians/', include('musicians.urls', namespace="bands")),
    path('bands/', include('bands.urls', namespace="musicians")),
    path('signup/', SignupView.as_view(), name='signup'),
    path('reset-password-done/', PasswordResetView.as_view(), name='reset-password-done'),
    path('reset-password/', PasswordResetDoneView.as_view(), name='reset-password'),
    path('reset-password-confirm/<uidb64>/<token>/', PasswordResetConfirmView.as_view(), name='reset-password-confirm'),
    path('reset-password-complete/', PasswordResetCompleteView.as_view(), name='reset-password-complete'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout')
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

crm/musicians/models.py
from unicodedata import category
from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth.models import AbstractUser

# Create your models here.

class User(AbstractUser):
    is_organisor = models.BooleanField(default=True)
    is_band = models.BooleanField(default=False)

class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username


class MusicianManager(models.Manager):
    def get_queryset(self):
        return super().get_queryset()


class Musician(models.Model):
    first_name =  models.CharField(max_length=20)
    last_name  = models.CharField(max_length=20)
    age = models.IntegerField(default=0)
    gigs_played = models.IntegerField(default=0)
    instruments_played = models.TextField(max_length=100)
    genres = models.TextField(max_length=100)
    organisation = models.ForeignKey(UserProfile, on_delete=models.CASCADE)
    band = models.ForeignKey("Band", null=True, blank=True, on_delete=models.SET_NULL)
    category = models.ForeignKey("Category", related_name="musicians", null=True, blank=True, on_delete=models.SET_NULL)
    date_added = models.DateTimeField(auto_now_add=True)
    phone_number = models.CharField(max_length=20)
    email = models.EmailField()
    converted_date = models.DateTimeField(null=True, blank=True)

    objects = MusicianManager()

    def __str__(self):
       return f"{self.first_name} {self.last_name}"

# def handle_upload_follow_ups(instance, filename):
#     return f"musician_followups/musician_{instance.musician.pk}/{filename}"

# class FollowUp(models.Model):
#     musician = models.ForeignKey(Musician, related_name="followups", on_delete=models.CASCADE)
#     date_added = models.DateTimeField(auto_now_add=True)
#     notes = models.TextField(blank=True, null=True)
#     file = models.FileField(null=True, blank=True, upload_to=handle_upload_follow_ups)

#     def __str__(self):
#         return f"{self.musician.first_name} {self.musician.last_name}"

   
class Band(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    organisation = models.ForeignKey(UserProfile, on_delete=models.CASCADE)

    def __str__(self):
       return self.user.email


class Category(models.Model):
    name = models.CharField(max_length=30)  # New, Contacted, Converted, Unconverted
    organisation = models.ForeignKey(UserProfile, on_delete=models.CASCADE)

    def __str__(self):
        return self.name


def post_user_created_signal(sender, instance, created, **kwargs):
    if created:
        UserProfile.objects.create(user=instance)
        

post_save.connect(post_user_created_signal, sender=User)

crm/musicians/forms.py
from django import forms
from .models import Musician
from .models import Band, Category
from django.contrib.auth.forms import get_user_model
from django.contrib.auth.forms import UserCreationForm, UsernameField

User = get_user_model()

class MusicianModelForm(forms.ModelForm):
 class Meta:
    model = Musician
    fields = (
        'first_name',
        'last_name',
        'age',
        'band'
    )



class MusicianForm(forms.Form):
    first_name = forms.CharField()
    last_name = forms.CharField()
    age = forms.IntegerField(min_value=0)

class CustomUserCreationForm(UserCreationForm):
    class Meta:
        model = User
        fields = ("username",)
        field_classes = {'username': UsernameField}

class AssignBandForm(forms.Form):
    band = forms.ModelChoiceField(queryset=Band.objects.none())

    def __init__(self, *args, **kwargs):
        request = kwargs.pop("request")
        bands = Band.objects.filter(organisation=request.user.userprofile)
        super(AssignBandForm, self).__init__(*args, **kwargs)
        self.fields["band"].queryset = bands

class   MusicianCategoryUpdateForm(forms.ModelForm):
    class Meta:
        model = Musician
        fields = (
            'category',
        )


class CategoryModelForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = (
            'name',
        )

crm/musicians/views.py
import logging
import datetime
from django import contrib
from django.contrib import messages
from django.core.mail import send_mail
from django.http.response import JsonResponse
from django.shortcuts import render, redirect, reverse
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponse
from django.views import generic
from bands.mixins import OrganisorAndLoginRequiredMixin
from .models import Musician, Band, Category
from .forms import (
    MusicianForm, 
    MusicianModelForm, 
    CustomUserCreationForm, 
    AssignBandForm, 
    MusicianCategoryUpdateForm,
    CategoryModelForm)


logger = logging.getLogger(__name__)


# CRUD+L - Create, Retrieve, Update and Delete + List


class SignupView(generic.CreateView):
    template_name = "registration/signup.html"
    form_class = CustomUserCreationForm

    def get_success_url(self):
        return reverse("login")


class LandingPageView(generic.TemplateView):
    template_name = "landing.html"


class MusicianListView(LoginRequiredMixin, generic.ListView):
    template_name = "musicians/musician_list.html"
    context_object_name = "musicians"

    def get_queryset(self):
        user = self.request.user
        # initial queryset of musicians for the entire organisation
        if user.is_organisor:
            queryset = Musician.objects.filter(
                organisation=user.userprofile, 
                band__isnull=False
            )
        else:
            queryset = Musician.objects.filter(
                organisation=user.band.organisation, 
                band__isnull=False
            )
            # filter for the band that is logged in
            queryset = queryset.filter(band__user=user)
        return queryset

    def get_context_data(self, **kwargs):
        context = super(MusicianListView, self).get_context_data(**kwargs)
        user = self.request.user
        if user.is_organisor:
            queryset = Musician.objects.filter(
                organisation=user.userprofile, 
                band__isnull=True
            )
            context.update({
                "unassigned_musicians": queryset
            })
        return context


def musician_list(request):
    musicians = Musician.objects.all()
    context = {
        "musicians": musicians
    }
    return render(request, "musicians/musician_list.html", context)


class MusicianDetailView(LoginRequiredMixin, generic.DetailView):
    template_name = "musicians/musician_detail.html"
    context_object_name = "musician"

    def get_queryset(self):
        user = self.request.user
        # initial queryset of musicians for the entire organisation
        if user.is_organisor:
            queryset = Musician.objects.filter(organisation=user.userprofile)
        else:
            queryset = Musician.objects.filter(organisation=user.band.organisation)
            # filter for the agent that is logged in
            queryset = queryset.filter(band__user=user)
        return queryset


def musician_detail(request, pk):
    musician = Musician.objects.get(id=pk)
    context = {
        "musician": musician
    }
    return render(request, "musicians/musician_detail.html", context)


class MusicianCreateView(OrganisorAndLoginRequiredMixin, generic.CreateView):
    template_name = "musicians/musician_create.html"
    form_class = MusicianModelForm

    def get_success_url(self):
        return reverse("musicians:musician-list")

    def form_valid(self, form):
        musician = form.save(commit=False)
        musician.organisation = self.request.user.userprofile
        musician.save()
        send_mail(
            subject="A musician has been created",
            message="Go to the site to see the new musician",
            from_email="test@test.com",
            recipient_list=["test2@test.com"]
        )
        messages.success(self.request, "You have successfully created a musician")
        return super(MusicianCreateView, self).form_valid(form)


def musician_create(request):
    form = MusicianModelForm()
    if request.method == "POST":
        form = MusicianModelForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("/musicians")
    context = {
        "form": form
    }
    return render(request, "musicians/musician_create.html", context)


class MusicianUpdateView(OrganisorAndLoginRequiredMixin, generic.UpdateView):
    template_name = "musicians/musician_update.html"
    form_class = MusicianModelForm

    def get_queryset(self):
        user = self.request.user
        # initial queryset of musicians for the entire organisation
        return Musician.objects.filter(organisation=user.userprofile)

    def get_success_url(self):
        return reverse("musicians:musician-list")

    def form_valid(self, form):
        form.save()
        messages.info(self.request, "You have successfully updated this musician")
        return super(MusicianUpdateView, self).form_valid(form)


def musician_update(request, pk):
    musician = Musician.objects.get(id=pk)
    form = MusicianModelForm(instance=musician)
    if request.method == "POST":
        form = MusicianModelForm(request.POST, instance=musician)
        if form.is_valid():
            form.save()
            return redirect("/musicians")
    context = {
        "form": form,
        "musician": musician
    }
    return render(request, "musicians/musician_update.html", context)


class MusicianDeleteView(OrganisorAndLoginRequiredMixin, generic.DeleteView):
    template_name = "musicians/musician_delete.html"

    def get_success_url(self):
        return reverse("musicians:musician-list")

    def get_queryset(self):
        user = self.request.user
        # initial queryset of musicians for the entire organisation
        return Musician.objects.filter(organisation=user.userprofile)


def musician_delete(request, pk):
    musician = Musician.objects.get(id=pk)
    musician.delete()
    return redirect("/musicians")


class AssignBandView(OrganisorAndLoginRequiredMixin, generic.FormView):
    template_name = "musicians/assign_band.html"
    form_class = AssignBandForm

    def get_form_kwargs(self, **kwargs):
        kwargs = super(AssignBandView, self).get_form_kwargs(**kwargs)
        kwargs.update({
            "request": self.request
        })
        return kwargs
        
    def get_success_url(self):
        return reverse("musicians:musician-list")

    def form_valid(self, form):
        band = form.cleaned_data["band"]
        musician = Musician.objects.get(id=self.kwargs["pk"])
        musician.band = band
        musician.save()
        return super(AssignBandView, self).form_valid(form)


class CategoryListView(LoginRequiredMixin, generic.ListView):
    template_name = "musicians/category_list.html"
    context_object_name = "category_list"

    def get_context_data(self, **kwargs):
        context = super(CategoryListView, self).get_context_data(**kwargs)
        user = self.request.user

        if user.is_organisor:
            queryset = Musician.objects.filter(
                organisation=user.userprofile
            )
        else:
            queryset = Musician.objects.filter(
                organisation=user.agent.organisation
            )

        context.update({
            "unassigned_lead_count": queryset.filter(category__isnull=True).count()
        })
        return context

    def get_queryset(self):
        user = self.request.user
        # initial queryset of musicians for the entire organisation
        if user.is_organisor:
            queryset = Category.objects.filter(
                organisation=user.userprofile
            )
        else:
            queryset = Category.objects.filter(
                organisation=user.agent.organisation
            )
        return queryset


class CategoryDetailView(LoginRequiredMixin, generic.DetailView):
    template_name = "musicians/category_detail.html"
    context_object_name = "category"

    def get_queryset(self):
        user = self.request.user
        # initial queryset of musicians for the entire organisation
        if user.is_organisor:
            queryset = Category.objects.filter(
                organisation=user.userprofile
            )
        else:
            queryset = Category.objects.filter(
                organisation=user.agent.organisation
            )
        return queryset


class CategoryCreateView(OrganisorAndLoginRequiredMixin, generic.CreateView):
    template_name = "musicians/category_create.html"
    form_class = CategoryModelForm

    def get_success_url(self):
        return reverse("musicians:category-list")

    def form_valid(self, form):
        category = form.save(commit=False)
        category.organisation = self.request.user.userprofile
        category.save()
        return super(CategoryCreateView, self).form_valid(form)


class CategoryUpdateView(OrganisorAndLoginRequiredMixin, generic.UpdateView):
    template_name = "musicians/category_update.html"
    form_class = CategoryModelForm

    def get_success_url(self):
        return reverse("musicians:category-list")

    def get_queryset(self):
        user = self.request.user
        # initial queryset of musicians for the entire organisation
        if user.is_organisor:
            queryset = Category.objects.filter(
                organisation=user.userprofile
            )
        else:
            queryset = Category.objects.filter(
                organisation=user.agent.organisation
            )
        return queryset


class CategoryDeleteView(OrganisorAndLoginRequiredMixin, generic.DeleteView):
    template_name = "musicians/category_delete.html"

    def get_success_url(self):
        return reverse("musicians:category-list")

    def get_queryset(self):
        user = self.request.user
        # initial queryset of musicians for the entire organisation
        if user.is_organisor:

crm/musicians/templates/musicians/assign_band.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}

<div class="max-w-lg mx-auto">
    <a class="hover:text-blue-500" href="{% url 'musicians:musician-list' %}">Go back to musicians</a>
    <div class="py-5 border-t border-gray-200">
        <h1 class="text-4xl text-gray-800">Assign a band to this musician</h1>
    </div>
    <form method="post" class="mt-5">
        {% csrf_token %}
        {{ form|crispy }}
        <button type='submit' class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">
            Submit
        </button>
    </form>
</div>

{% endblock content %}

crm/musicians/templates/musicians/category_create.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}

<div class="max-w-lg mx-auto">
    <a class="hover:text-blue-500" href="{% url 'musicians:category-list' %}">Go back to categories</a>
    <div class="py-5 border-t border-gray-200">
        <h1 class="text-4xl text-gray-800">Create a new category</h1>
    </div>
    <form method="post" class="mt-5">
        {% csrf_token %}
        {{ form|crispy }}
        <button type='submit' class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">
            Submit
        </button>
    </form>
</div>

{% endblock content %}

crm/musicians/templates/musicians/musician_category_update.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}

<section class="text-gray-700 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
      <div class="lg:w-4/5 mx-auto flex flex-wrap">
        <div class="w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
            <h2 class="text-sm title-font text-gray-500 tracking-widest">Musician</h2>
            <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ musician.first_name }} {{ musician.last_name }}</h1>
            <div class="flex mb-4">
                <a href="{% url 'musicians:musician-detail' musician.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                    Overview
                </a>
                <a href="{% url 'musicians:musician-category-update' musician.pk %}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">
                    Category
                </a>
                <a href="{% url 'musicians:musician-update' musician.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                    Update Details
                </a>
            </div>
            <form form method="post">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">Submit</button>
            </form>
        </div>
      </div>
    </div>
  </section>
{% endblock content %}

crm/musicians/templates/musicians/musician_detail.html
{% extends "base.html" %}
{% block content %}

<section class="text-gray-600 body-font overflow-hidden">
  <div class="container px-5 py-24 mx-auto">
    <div class="lg:w-4/5 mx-auto flex flex-wrap">
      <div class="lg:w-1/2 w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
        <h2 class="text-sm title-font text-gray-500 tracking-widest">Musician</h2>
        <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{musician.first_name}} {{musician.last_name}}</h1>
        <div class="flex mb-4">
          <a href="{% url 'musicians:musician-detail' musician.pk %}"class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">Overview</a>
          <a class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Reviews</a>
          <a href="{% url 'musicians:musician-update' musician.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">Update Details</a>
        </div>
        <p class="leading-relaxed mb-4">Fam locavore kickstarter distillery. Mixtape chillwave tumeric sriracha taximy chia microdosing tilde DIY. XOXO fam inxigo juiceramps cornhole raw denim forage brooklyn. Everyday carry +1 seitan poutine tumeric. Gastropub blue bottle austin listicle pour-over, neutra jean.</p>
        <div class="flex border-t border-gray-200 py-2">
          <span class="text-gray-500">Age</span>
          <span class="ml-auto text-gray-900">{{musician.age}}</span>
        </div>
        <div class="flex border-t border-gray-200 py-2">
          <span class="text-gray-500">Location</span>
          <span class="ml-auto text-gray-900">Dummy Location</span>
        </div>
        <div class="flex border-t border-b mb-6 border-gray-200 py-2">
          <span class="text-gray-500">Cell phone</span>
          <span class="ml-auto text-gray-900">+34343434</span>
        </div>
        <div class="flex">
          <button class="flex ml-auto text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">Button</button>
          <button class="rounded-full w-10 h-10 bg-gray-200 p-0 border-0 inline-flex items-center justify-center text-gray-500 ml-4">
            <svg fill="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-5 h-5" viewBox="0 0 24 24">
              <path d="M20.84 4.61a5.5 5.5 0 00-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 00-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 000-7.78z"></path>
            </svg>
          </button>
        </div>
      </div>
    </div>
  </div>
</section>
{% endblock content %}

crm/musicians/templates/musicians/musician_list.html
{% extends "base.html" %}

{% block content %}

<section class="text-gray-700 body-font">
    <div class="container px-5 py-24 mx-auto flex flex-wrap">
        <div class="w-full mb-6 py-6 flex justify-between items-center border-b border-gray-200">
            <div>
                <h1 class="text-4xl text-gray-800">Musicians</h1>
                <a class="text-gray-500 hover:text-blue-500" href="{% url 'musicians:category-list' %}">
                    View categories
                </a>
            </div>
            {% if request.user.is_organisor %}
            <div>
                <a class="text-gray-500 hover:text-blue-500" href="{% url 'musicians:musician-create' %}">
                    Create a new musician
                </a>
            </div>
            {% endif %}
        </div>

        <div class="flex flex-col w-full">
            <div class="-my-2 overflow-x-auto sm:-mx-6 lg:-mx-8">
            <div class="py-2 align-middle inline-block min-w-full sm:px-6 lg:px-8">
                <div class="shadow overflow-hidden border-b border-gray-200 sm:rounded-lg">
                <table class="min-w-full divide-y divide-gray-200">
                    <thead class="bg-gray-50">
                        <tr>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                            First Name
                            </th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                            Last Name
                            </th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                            Age
                            </th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                            Email
                            </th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                            Cell Phone Number
                            </th>
                            <th scope="col" class="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                            Category
                            </th>
                            <th scope="col" class="relative px-6 py-3">
                            <span class="sr-only">Edit</span>
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for musician in musicians %}
                            <tr class="bg-white">
                                <td class="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                                    <a class="text-blue-500 hover:text-blue-800" href="{% url 'musicians:musician-detail' musician.pk %}">{{ musician.first_name }}</a>
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                    {{ musician.last_name }}
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                    {{ musician.age }}
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                    {{ musician.email }}
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                                    {{ musician.phone_number }}
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap">
                                    {% if musician.category %}
                                        <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-green-100 text-green-800">
                                            {{ musician.category.name }}
                                        </span>
                                    {% else %}
                                        <span class="px-2 inline-flex text-xs leading-5 font-semibold rounded-full bg-gray-100 text-gray-800">
                                            Unassigned
                                        </span>
                                    {% endif %}
                                </td>
                                <td class="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                                    <a href="{% url 'musicians:musician-update' musician.pk %}" class="text-indigo-600 hover:text-indigo-900">
                                        Edit
                                    </a>
                                </td>
                            </tr>

                        {% empty %}

                        <p>There are currently no musicians</p>

                        {% endfor %}
                    </tbody>
                </table>
                </div>
            </div>
            </div>
        </div>
  
        {% if unassigned_musicians.exists %}
            <div class="mt-5 flex flex-wrap -m-4">
                <div class="p-4 w-full">
                    <h1 class="text-4xl text-gray-800">Unassigned musicians</h1>
                </div>
                {% for musician in unassigned_musicians %}
                <div class="p-4 lg:w-1/2 md:w-full">
                    <div class="flex border-2 rounded-lg border-gray-200 p-8 sm:flex-row flex-col">
                        <div class="w-16 h-16 sm:mr-8 sm:mb-0 mb-4 inline-flex items-center justify-center rounded-full bg-indigo-100 text-indigo-500 flex-shrink-0">
                            <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-8 h-8" viewBox="0 0 24 24">
                                <path d="M22 12h-4l-3 9L9 3l-3 9H2"></path>
                            </svg>
                        </div>
                        <div class="flex-grow">
                            <h2 class="text-gray-900 text-lg title-font font-medium mb-3">
                                {{ musician.first_name }} {{ musician.last_name }}
                            </h2>
                            <p class="leading-relaxed text-base">
                                {{ musician.description }}
                            </p>
                            <a href="{% url 'musicians:assign-band' musician.pk %}" class="mt-3 text-indigo-500 inline-flex items-center">
                                Assign a band
                                <svg fill="none" stroke="currentColor" stroke-linecap="round" stroke-linejoin="round" stroke-width="2" class="w-4 h-4 ml-2" viewBox="0 0 24 24">
                                    <path d="M5 12h14M12 5l7 7-7 7"></path>
                                </svg>
                            </a>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        {% endif %}
    </div>
</section>
{% endblock content %}

crm/musicians/templates/musicians/musician_update.html
{% extends "base.html" %}
{% load tailwind_filters %}

{% block content %}

<section class="text-gray-700 body-font overflow-hidden">
    <div class="container px-5 py-24 mx-auto">
      <div class="lg:w-4/5 mx-auto flex flex-wrap">
        <div class="w-full lg:pr-10 lg:py-6 mb-6 lg:mb-0">
            <h2 class="text-sm title-font text-gray-500 tracking-widest">Musician</h2>
            <h1 class="text-gray-900 text-3xl title-font font-medium mb-4">{{ musician.first_name }} {{ musician.last_name }}</h1>
            <div class="flex mb-4">
                <a href="{% url 'musicians:musician-detail' musician.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                    Overview
                </a>
                <a href="{% url 'musicians:musician-category-update' musician.pk %}" class="flex-grow border-b-2 border-gray-300 py-2 text-lg px-1">
                    Category
                </a>
                <a href="{% url 'musicians:musician-update' musician.pk %}" class="flex-grow text-indigo-500 border-b-2 border-indigo-500 py-2 text-lg px-1">
                    Update Details
                </a>
            </div>
            <form method="post" enctype="multipart/form-data">
                {% csrf_token %}
                {{ form|crispy }}
                <button type="submit" class="w-full text-white bg-blue-500 hover:bg-blue-600 px-3 py-2 rounded-md">Submit</button>
            </form>
            <div class="mt-5 py-5 border-t border-gray-200">
                <a href="{% url 'musicians:musician-delete' musician.pk %}" class="w-1/2 mt-3 text-white bg-indigo-500 border-0 py-2 px-6 focus:outline-none hover:bg-indigo-600 rounded">
                    Delete
                </a>
            </div>
        </div>
      </div>
    </div>
  </section>
{% endblock content %}